# Dependency age
minimumReleaseAge: 4320 # 3 days - same as renovate
minimumReleaseAgeExclude:
  - "@foldland/*"
  - "@strapi/*"

registries:
  default: https://registry.npmjs.org/
  "@foldland": https://npm.registry.foldland.io/

# Dependency resolution
savePrefix: "^"
resolutionMode: "highest"
strictPeerDependencies: true
preferFrozenLockfile: true
autoDedupe: true
dedupePeers: true

# node version
engineStrict: true
ignorePnpmfile: true

# Security
blockExoticSubdeps: true
hoist: false
hoistWorkspacePackages: false
verifyDepsBeforeRun: "install"

allowBuilds:
  "@swc/core": false
  core-js-pure: false
  esbuild: false
  sharp: false

# broken strapi peers
peerDependencyRules:
  allowedVersions:
    codemirror: 5.65.21

overrides:
  axios@>=1.13.0 <1.20.0: ^1.20.0
  handlebars@>=4.0.0 <=4.7.9: ^4.7.10
  nodemailer@<=10.0.5: ^10.0.6
  sharp@<0.35.5: ^0.35.5
  shell-quote@>=1.8.4 <1.11.0: ^1.11.0
  vite@<=6.4.2: ^6.4.3
  webpack-dev-middleware@<7.4.6: ^7.4.6
