# Dependency age
minimumReleaseAge: 4320 # 3 days - same as renovate
minimumReleaseAgeExclude:
  - "@foldland/*"
  - "@strapi/*"
  # security issues
  - vite@6.4.3
  - tar@7.5.19
  - shell-quote@1.8.5
  - sharp@0.35.0

registries:
  default: https://registry.npmjs.org/
  "@foldland": https://npm.registry.foldland.io/

# Dependency resolution
savePrefix: "^"
resolutionMode: "highest"
strictPeerDependencies: false # TODO: broken strapi/pnpm stuff
preferFrozenLockfile: true

# node version
engineStrict: true
ignorePnpmfile: true
# pnpm version
packageManagerStrict: true
packageManagerStrictVersion: true

# Security
blockExoticSubdeps: true
hoist: false
hoistWorkspacePackages: false
verifyDepsBeforeRun: "install"

overrides:
  zod@3.25.67: ^3.25.76
  # security issues
  sharp@<0.35.0: ^0.35.0
  shell-quote@^1.0.0: ^1.8.5
  tar@^7.0.0: ^7.5.19
  vite@<=6.4.2: ^6.4.3

allowBuilds:
  "@swc/core": false
  core-js-pure: false
  esbuild: false
  sharp: false
