FROM mcr.microsoft.com/devcontainers/typescript-node:24@sha256:5d4dfbb91a7d76906484ff55f69a883eb8ed3c2628ab5611a826c94b06f09fe2

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install gnupg2
