FROM mcr.microsoft.com/devcontainers/typescript-node:24@sha256:0cbad76d1987fd35fd78cbc58cbe8c2aa93a8daa45411e52c6c6b63ea2dae202

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install gnupg2
