FROM mcr.microsoft.com/devcontainers/typescript-node:24@sha256:627da5f4ab0dfa32c23cd93a10925c20bf92e5f2814cec74cde8520fb33e3ec4

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install gnupg2
